### ISSUE TITLE
Minetest USER PATH patch does not work properly

### ISSUE THREAD

**Issue by Eonfge** [flathub/net.minetest.Minetest#47]
## Related lines;
- https://github.com/flathub/net.minetest.Minetest/blob/master/net.minetest.Minetest.yaml#L63
- https://github.com/flathub/net.minetest.Minetest/blob/master/net.minetest.Minetest.yaml#L70

This does not work properly when saving or loading files. When I run a game directly from the CLI (bypassing) the run-script, I can see my previously saved worlds and mods, but when I start using the desktop shortcut, I can't load any of my previously saved worlds!

**Comment by rubenwardy** [comment]
Please ensure you've updated to the latest version, as I've just fixed a bug related to this

**Comment by rubenwardy** [comment]
> I'm surprised so much complexity is needed here. Flatpaks should be able to use $HOME/.var/app without any tweaks to the upstream code. Even in games last updated 10 years ago (and not caring for the XDG specification), it works fine in my experience.

The problem is that Minetest defaults to `~/.minetest` inside the flatpak, which causes issues with xdg-desktop-portal mapping to the host. If [this issue](https://github.com/flatpak/xdg-desktop-portal/issues/591) was solved, there would be no need for any change here. The patch and wrapper script is just to use an environment variable to use `~/.var/app/net.minetest.Minetest/.minetest` inside the flatpak
